### PR TITLE
[MIG][13.0] Migrate `l10n_fi_invoice_delivery_date` from 12.0 to 13.0

### PR DESCRIPTION
**Pull request by Tatider**

### CODE REVIEW

**Comment by mlaitinen** [comment]
@Tatider Please check the branches

**Comment by Tatider** [comment]
@mlaitinen Destination branch updated.

But list of commits still contain some inverting commits... Because of way how branch `13.0` were created (checkout from `12.0` with removing of all modules.). So MR contain "fixuped" with commit message "13.0"

**Comment by mlaitinen** [comment]
@aisopuro hjälp. What do we do in this case when there are unwanted commits in this MR? Rebase?

@Tatider OCA used to do migrations by forking the previous version branch and by marking the modules non-installable. I believe this caused some problems and they moved to the model in which the new version branch is empty. IIRC we also had some problems with the non-installable modules. Even when they're marked that way, some of them still caused errors in Odoo.

**Comment by aisopuro** [comment]
`git rebase -i` will allow you to simply remove commits you don't want. Just make sure your diff is still correct.

**Comment by mlaitinen** [comment]
Still has conflicts

**Comment by aisopuro** [comment]
It seems that nothing has been done here. I can try to do the necessary changes if someone can tell me exactly which commits are not wanted in this PR.

**Comment by Tatider** [comment]
@aisopuro There are no unwanted commits. But [this one](https://github.com/avoinsystems/avoinsystems-addons/pull/14/commits/8f06c491a5c58f7f1080ffc9d104496531174267) will change what @mlaitinen [made before](https://github.com/avoinsystems/avoinsystems-addons/commit/dd335af148c14546a8bf0d4e9574636997eede9d) -- restore `l10n_fi_invoice_delivery_date` files which were removed.

**Comment by mlaitinen** [comment]
Replaced by #18

**Pull request closed without merging**
